                                                     This is the START

In [ ]:
45 + 72

117

In [ ]:
5* (12.7-4) / 2

21.75

In [ ]:
5* 12.7-4 / 2

61.5

In [ ]:
5*(3+4)

35

In [ ]:
5*3+4

19

In [ ]:
x=7
y=3
x+y

10

In [ ]:
Total=x+y
Total

NameError: ignored

In [ ]:
type (45)

In [ ]:
type (12.7)

In [ ]:
10.8+12.2+0.2

In [ ]:
Total = 10.8+12.2+0.2
Total

In [ ]:
7*8

In [ ]:
3*(4-5)

-3

In [ ]:
3*4-5

7

In [ ]:
4**3**2

262144

In [ ]:
(4**3)**2

4096

In [ ]:
4**(3**2)

262144

In [ ]:
print('Hi!')

Hi!


In [ ]:
print("Hi!")

Hi!


In [ ]:
print('A' , 'V' , 'I' , 'Y' , 'A')

A V I Y A


In [ ]:
print('Display "hi" in quotes')

Display "hi" in quotes


In [ ]:
print('Display 'hi' in quotes')

SyntaxError: ignored

In [ ]:
7>4

True

In [ ]:
7<4

False

In [ ]:
x=3
1 <= x <= 5

True

In [ ]:
x=10
1 <= x <= 5

False

In [ ]:
7=<10

SyntaxError: ignored

In [ ]:
print(5<9 , 5<=9 , 5>9 , 5>=9 , 5==9 , 5!=9)

True True False False False True


In [ ]:
type(7)

int

In [ ]:
type(4.1)

float

In [ ]:
type("dog")

str

In [ ]:
s=7
s+10

17

In [ ]:
s=7
s+10
s

7

In [ ]:
import numpy as np
numbers = np.array([2,3,5,7,11])
type(numbers)

numpy.ndarray

In [ ]:
import numpy as np
numbers = np.array([2,3,5,7,11])
numbers

array([ 2,  3,  5,  7, 11])

In [ ]:
np.array ([[1,2,3] , [ 4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np
integers = np.array ([[1,2,3] , [ 4,5,6]])
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
floats = np.array ([0.0,0.1,0.2,0.3,0.4])
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [ ]:
integers.dtype

dtype('int64')

In [ ]:
floats.dtype

dtype('float64')

In [ ]:
integers.ndim

2

In [ ]:
floats.ndim

1

In [ ]:
integers.shape

(2, 3)

In [ ]:
floats.shape

(5,)

In [ ]:
integers.size

6

In [ ]:
floats.size

5

In [ ]:
integers.itemsize

8

In [ ]:
floats.itemsize

8

In [ ]:
min(47, 8, 9)

8

In [ ]:
max(56, 76, 54)

76

In [ ]:
if 0:
    print('Bla bla')

In [ ]:
if 1:
    print('Bla bla')

Bla bla


In [ ]:
product=3

In [ ]:
while product <= 50:
  product = product*3

In [ ]:
product

81

In [ ]:
for charecter in 'Programming':
  print(charecter , end='  ')

P  r  o  g  r  a  m  m  i  n  g  

In [ ]:
print(1, 2, 3, sep = ', ')

1, 2, 3


In [ ]:
total=0
for number in [2, -3, 0, 17, 9]:
    total = total + number
total

25

In [ ]:
name = "checkuslovakya"
count = 0
for literal in name :
  if (literal == 'c'):
    count = count + 1
print(count)

2


In [ ]:
name = "agrakadabra"
count_a = 0
count_c = 0
for literal in name :
  if (literal == 'a'):
    count_a = count_a + 1
for literal in name :
  if (literal == 'r'):
    count_c = count_c + 1
print(count_a)
print(count_c)

5
2


In [ ]:
name = "agrakadabra"
count_a = 0
count_c = 0
for literal in name :
  if (literal == 'r'):
    count_c = count_c + 1
  else if (literal == 'a'):
    count_a = count_a + 1
print(count_a)
print(count_c)

5
2


In [ ]:
name = "something new"
count = 0
for literal in name :
  if (literal == 's'):
    count = count + 1
  if (literal == 'e'):
    count = count + 1
  if (literal == 'n'):
    count = count + 1
print(count)

5


In [ ]:
name = "something new"
count = 0
for literal in name :
  if (literal == 's'  or literal == 'e' or literal == 'n' ):
    count = count + 1
print(count)

5


In [ ]:
name = "something new"
count = 0
count=name.count
print(count)

1


In [ ]:
word = "tree"
count = 0
for literal in word :
  if (literal == 'e'):
    count = count + 1
  if count == 2:
   print("it repeats")

it repeats


In [ ]:
word = "ball"
check = 0
for literal in word:
  if (literal == check):
    print("It repeats")
  check = literal

It repeats


In [ ]:
one = "Aviya"
Two = "Daniel"
print(one +" "+ Two)

Aviya Daniel


In [ ]:
word = "box"
ind = 0
charecter = "o"
for literal in word:
  if (literal == charecter):
    break
  ind=ind+1
  print(ind)

1


In [ ]:
whole = 0
for number in [1, 2, 3, 4, 5]:
  whole += number
print (whole)

15


In [ ]:
x = 12
x *=12
x

144

In [ ]:
n1 = 7
n2 = 5
print(f' {n1} times {n2} is {n1 * n2}')

 7 times 5 is 35


In [ ]:
for number in range(4, 11):
  print(number, end = " ")

4 5 6 7 8 9 10 

In [ ]:
for number in range(10, 20, 4):
  print(number, end = " ")

10 14 18 

In [ ]:
for number in range(48, 28, -5):
  print(number, end = " ")

48 43 38 33 

In [ ]:
for number in range(99, -1, -11):
  print(number, end = "    ")

99    88    77    66    55    44    33    22    11    0    

In [ ]:
a = 112.31
print(f'{a:.20f}')

112.31000000000000227374


In [ ]:
from decimal import Decimal
p = Decimal('1000.00')
p

Decimal('1000.00')

In [ ]:
r = Decimal('0.05')
r

Decimal('0.05')

In [ ]:
x = Decimal('10.5')
y = Decimal('2')
x + y

Decimal('12.5')

In [ ]:
x // y

Decimal('5')

In [ ]:
x += y
x

Decimal('24.5')

In [ ]:
for year in range(1, 11):
  a = p * (1 + r) ** year
  print(f'{year:>2}{a:10.2f}')

 1   1050.00
 2   1102.50
 3   1157.62
 4   1215.51
 5   1276.28
 6   1340.10
 7   1407.10
 8   1477.46
 9   1551.33
10   1628.89


In [ ]:
def square(number):
  """Calculate the square of a number. """
  return number ** 2

In [ ]:
square(8)

64

In [ ]:
square(5.7)

32.49

In [ ]:
square?

In [ ]:
square??

In [ ]:
def maximum(value1, value2, value3):
  """Return the maximum of three values. """
  max_value = value1
  if value2 > max_value:
    max_value = value2
  if value3 > max_value:
    max_value = value3
    return max_value

In [ ]:
maximum(2, 4, 9)

9

In [ ]:
maximum(5.8, 8.7, 6.9)

In [ ]:
maximum('egg', 'red', 'zebra')

'zebra'

In [ ]:
import random
for roll in range(10):
  print(random.randrange(1, 7), end = '  ')

6  3  6  2  2  3  3  2  6  6  

In [ ]:
sum?

In [ ]:
import math
math.acos?

In [ ]:
math.sqrt(400)

20.0

In [ ]:
math.fabs(-684)

684.0

In [ ]:
def r_a(l=2, b=3):
  """Return a rectangle's area"""
  return l * b

In [ ]:
r_a()

6

In [ ]:
r_a(10)

30

In [ ]:
r_a(5,9)

45

In [ ]:
def r_a(l, b):
  """Return a rectangle's area"""
  return l * b

In [ ]:
r_a

<function __main__.r_a(l, b)>

In [ ]:
r_a(4, 6)

24

In [ ]:
r_a(8.9, 4.7)

41.830000000000005

In [ ]:
def average(*args):
  return sum(args) / len(args)

In [ ]:
average(48, 8)

28.0

In [ ]:
grades = [10, 10, 10, 5, 7, 2, 9, 3, 8, 6]
average(*grades)

7.0

In [ ]:
n = 'Aviya'


In [ ]:
n.upper()

'AVIYA'

In [ ]:
n.lower()

'aviya'

In [ ]:
c = 7
id(c)

139737541198256

In [ ]:
x = 7

In [ ]:
def cube(number):
  print('number is x:', number is x)
  return number ** 3

In [ ]:
cube(x)

number is x: True


343

In [ ]:
l = [8, 76, -49, 72, -27]

In [ ]:
l

[8, 76, -49, 72, -27]

In [ ]:
l[2]

-49

In [ ]:
l[4]

-27

In [ ]:
l[0]

8

In [ ]:
len(l)

5

In [ ]:
l[-3]

-49

In [ ]:
l[-2]

72

In [ ]:
l[3]

72

In [ ]:
a = 2
b = 1

In [ ]:
l[a + b]

72

In [ ]:
l[2] =  27

In [ ]:
l

[8, 76, 27, 72, -27]

In [ ]:
l[4] = 49

In [ ]:
l

[8, 76, 27, 72, 49]

In [ ]:
l[3] = 38

In [ ]:
l

[8, 76, 27, 38, 49]

In [ ]:
n = 'dates arp tasty'

In [ ]:
n

'dates arp tasty'

In [ ]:
n[7]

'r'

In [ ]:
n[8] = 'e'

TypeError: ignored

In [ ]:
n = 'dates are tasty'

In [ ]:
n

'dates are tasty'

In [ ]:
something = []

In [ ]:
something

[]

In [ ]:
for number in range(1, 11):
  something += [number]

In [ ]:
something

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
ohio = []

In [ ]:
ohio += 'north america'

In [ ]:
ohio

['north america',
 'n',
 'o',
 'r',
 't',
 'h',
 ' ',
 'a',
 'm',
 'e',
 'r',
 'i',
 'c',
 'a']

In [ ]:
f, s = 'do'

In [ ]:
print(f'{f},{s}')

d,o


In [ ]:
letters = ['A', 'V', 'I', 'Y', 'A']

In [ ]:
list(enumerate(letters))

[(0, 'A'), (1, 'V'), (2, 'I'), (3, 'Y'), (4, 'A')]

In [ ]:
numbers = [2, 4, 6, 8, 10]

In [ ]:
numbers[1:4]

[4, 6, 8]

In [ ]:
numbers[:3]

[2, 4, 6]

In [ ]:
numbers[2:]

[6, 8, 10]

In [ ]:
numbers[2:len(numbers)]

[6, 8, 10]

In [ ]:
numbers[:]

array([ 2,  3,  5,  7, 11])

In [ ]:
numbers[::2]

array([ 2,  5, 11])

In [ ]:
numbers = [98, 0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 9]

In [ ]:
numbers

[98, 0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 9]

In [ ]:
del numbers[-2]

In [ ]:
numbers

[98, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
del numbers[0:2]

In [ ]:
numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
del numbers

In [ ]:
numbers

NameError: ignored

In [ ]:
n = [9, 6, 8, 3, 10, 2, 7, 1, 5, 0, 4]

In [ ]:
n.sort()

In [ ]:
n

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
n.sort(reverse = True)

In [ ]:
n

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [ ]:
n = [9, 6, 8, 3, 10, 2, 7, 1, 5, 0, 4]

In [ ]:
a_n = sorted(n)

In [ ]:
a_n

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
l = "efahbdgc"

In [ ]:
a_l = sorted(l)

In [ ]:
a_l

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [ ]:
ldf = [0, 2, 4, 6, 8]

In [ ]:
ldf *=3

In [ ]:
ldf

[0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8]

In [ ]:
ldf.index(4)

2

In [ ]:
ldf.index(2, 4)

6

In [ ]:
ldf.index(8, 4, 8)

4

In [ ]:
2345 in ldf

False

In [ ]:
6 in ldf

True

In [ ]:
345 not in ldf

True

In [ ]:
4 not in ldf

False

In [ ]:
search = ['e', 'a', 'r', 'c', 'h']

In [ ]:
search.insert(0, 's')

In [ ]:
search

['s', 'e', 'a', 'r', 'c', 'h']

In [ ]:
search.append('nothing')

In [ ]:
search

['s', 'e', 'a', 'r', 'c', 'h', 'nothing']

In [ ]:
efg = [1, 2, 3, 4, 5, 6]

In [ ]:
efg.extend((7, 8, 9, 10))

In [ ]:
efg

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
efg.remove(10)

In [ ]:
efg

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
'flow' > 'Flow'

True

In [ ]:
ord('F')

70

In [ ]:
ord('f')

102

In [ ]:
VIB = ['Violat', 'indigo', 'Blue']

In [ ]:
min(VIB, key=lambda s: s.lower())

'Blue'

In [ ]:
max(VIB, key=lambda s: s.lower())

'Violat'

In [ ]:
list1 = []

In [ ]:
for item in range (1, 11):
    list1.append(item)

In [ ]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list2 = [item for item in range(1, 6)]

In [ ]:
list2

[1, 2, 3, 4, 5]

In [ ]:
list3 = [item * 3 for item in range (1, 4)]

In [ ]:
list3

[3, 6, 9]

In [ ]:
list4 = [item for item in range(1, 21) if item % 2 == 0]

In [ ]:
list4

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
list5 = ['one', 'two', 'three', 'four', 'five']

In [ ]:
list51 = [item.upper() for item in list5]

In [ ]:
list51

['ONE', 'TWO', 'THREE', 'FOUR', 'FIVE']

In [ ]:
country_codes = {'Finland' : 'fi' , 'South America' : 'za' ,
                 'Nepal' : 'np' , 'India' : 'in'}

In [ ]:
country_codes

{'Finland': 'fi', 'South America': 'za', 'Nepal': 'np', 'India': 'in'}

In [ ]:
len(country_codes)

4

In [ ]:
if country_codes:
  print('country_codes is not empty')
else:
  print('country_codes is empty')


country_codes is not empty


In [ ]:
country_codes.clear()

In [ ]:
country_codes

{}

In [ ]:
if country_codes:
  print('country_codes is not empty')
else:
  print('country_codes is empty')

country_codes is empty


In [ ]:
states = {'Himachal Pradesh': 'H.P.', 'Uttar Pradesh': 'U.P.', 'Madhya Pradesh': 'M.P.'}

In [ ]:
states

{'Himachal Pradesh': 'H.P.', 'Uttar Pradesh': 'U.P.', 'Madhya Pradesh': 'M.P.'}

In [ ]:
dpm = {'June': 30, 'July': 31, 'August': 31}

In [ ]:
dpm

{'June': 30, 'July': 31, 'August': 31}

In [ ]:
for month, days in dpm.items():
  print(f' {month} has {days} days')

 June has 30 days
 July has 31 days
 August has 31 days


In [ ]:
RN = {'I': 1, 'II': 2, 'III': 3, 'V': 6, 'X': 100}

In [ ]:
RN

{'I': 1, 'II': 2, 'III': 3, 'V': 6, 'X': 100}

In [ ]:
RN['V']

6

In [ ]:
RN['V'] = 5

In [ ]:
RN['X']

100

In [ ]:
RN['X'] = 10

In [ ]:
RN

{'I': 1, 'II': 2, 'III': 3, 'V': 5, 'X': 10}

In [ ]:
c_f = {'mango' : 'red', 'guava' : 'green', 'grapes' : 'purple', 'plum' : 'orange', 'banana' : 'yellow'}

In [ ]:
c_f['mango']

'red'

In [ ]:
c_f['plum']

'red'

In [ ]:
c_f['mango'] = 'yellow'

In [ ]:
c_f['plum'] = 'red'

In [ ]:
c_f['banana'] = 'yellow'

In [ ]:
c_f['chiku'] = 'brown'

In [ ]:
c_f

{'mango': 'yellow',
 'guava': 'green',
 'grapes': 'purple',
 'plum': 'red',
 'banana': 'yellow',
 'chiku': 'brown'}

In [ ]:
len(c_f)

6

In [ ]:
for fruit, color in c_f.items():
  print(f' {fruit} is {color} in color')

 mango is yellow in color
 guava is green in color
 grapes is purple in color
 plum is red in color
 banana is yellow in color
 chiku is brown in color


In [ ]:
colors = {'red', 'yellow', 'blue', 'red', 'green', 'purple', 'black', 'yellow', 'white'}

In [ ]:
len(colors)

7

In [ ]:
colors

{'black', 'blue', 'green', 'purple', 'red', 'white', 'yellow'}

In [ ]:
'green' in colors

True

In [ ]:
'cyan' in colors

False

In [ ]:
'green' not in colors

False

In [ ]:
'cyan' not in colors

True

In [ ]:
for color in colors:
  print(color.upper(), end=' ')

RED BLUE BLACK YELLOW WHITE PURPLE GREEN 

In [ ]:
{1, 2, 3} == {2, 3, 1}

True

In [ ]:
{1, 2, 3} == {2, 3, 14}

False

In [ ]:
{1, 2, 3} != {2, 3, 14}

True

In [ ]:
{1, 2, 3} < {5, 8, 2, 3, 1}

True

In [ ]:
{1, 2, 3}.issubset({2, 3, 1})

True

In [ ]:
{1, 2, 3, 4, 5} > {2, 3, 1}

True

In [ ]:
{1, 2, 3} > {2, 3, 1}

False

In [ ]:
{1, 2, 3}.union([2, 3, 1])

{1, 2, 3}

In [ ]:
{1, 2, 3, 9, 10}.union([2, 3, 4, 5, 6, 7, 8])

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [ ]:
{7, 2, 4} & {2, 5, 8}

{2}

In [ ]:
{1, 2, 3}.intersection([1, 2, 5, 6, 8])

{1, 2}

In [ ]:
numbers = {1, 1, 2, 3, 3, 4, 5, 5, 6, 7, 7, 8, 9, 9, 10}

In [ ]:
even = {item for item in numbers if item % 2 == 0}

In [ ]:
numbers

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [ ]:
even

{2, 4, 6, 8, 10}

In [ ]:
nos = {2, 4, 6, 8}

In [ ]:
nos.update(range(10))

In [ ]:
nos

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [ ]:
nos.add(10)

In [ ]:
nos.add(13)

In [ ]:
nos

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13}

In [ ]:
nos.remove(13)

In [ ]:
nos = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13}

In [ ]:
nos.pop()

0

In [ ]:
nos

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13}

In [ ]:
nos.clear()

In [ ]:
nos

set()

In [ ]:
import numpy as np

In [ ]:
num = np.array([1, 2, 3, 4, 5])

In [ ]:
num

array([1, 2, 3, 4, 5])

In [ ]:
type(num)

numpy.ndarray

In [ ]:
nos = np.array([[1, 2, 3] , [4, 5, 6]])

In [ ]:
np.array([[2, 4, 6, 8, 10] , [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [ ]:
num.shape

(5,)

In [ ]:
nos.shape

(2, 3)

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.full((3, 6), 3)

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [ ]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.arange(1, 51).reshape(5, 10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [ ]:
import numpy as np

In [ ]:
grades = np.array([[6, 5, 9], [7, 10, 8],
                   [10, 7, 9], [8, 6, 9]])

In [ ]:
grades

array([[ 6,  5,  9],
       [ 7, 10,  8],
       [10,  7,  9],
       [ 8,  6,  9]])

In [ ]:
grades.sum()

94

In [ ]:
grades.min()

5

In [ ]:
grades.max()

10

In [ ]:
grades.mean()

7.833333333333333

In [ ]:
grades.std()

1.5723301886761005

In [ ]:
grades.var()

2.472222222222222

In [ ]:
grades.mean(axis = 0)

array([7.75, 7.  , 8.75])

In [ ]:
grades.mean(axis = 1)

array([6.66666667, 8.33333333, 8.66666667, 7.66666667])

In [ ]:
grades.mean?

In [ ]:
import numpy as np

In [ ]:
grades

array([[ 6,  5,  9],
       [ 7, 10,  8],
       [10,  7,  9],
       [ 8,  6,  9]])

In [ ]:
list9 = ([[6, 5, 9], [7, 10, 8],
                   [10, 7, 9], [8, 6, 9]])

In [ ]:
np.array = [4, 5, 6]

In [ ]:
list9[3],[2]

([8, 6, 9], [2])

In [ ]:
l1 = []

In [ ]:
for item in range(1, 6):
  l1.append(item)

In [ ]:
l1

[1, 2, 3, 4, 5]

In [ ]:
grades = np.array([[6, 5, 9], [7, 10, 8],
                   [10, 7, 9], [8, 6, 9]])

In [ ]:
grades

array([[ 6,  5,  9],
       [ 7, 10,  8],
       [10,  7,  9],
       [ 8,  6,  9]])

In [ ]:
grades[2, 1]

7

In [ ]:
grades[2]

array([10,  7,  9])

In [ ]:
grades[1:3]

array([[ 7, 10,  8],
       [10,  7,  9]])

In [ ]:
grades[0:3]


array([[ 6,  5,  9],
       [ 7, 10,  8],
       [10,  7,  9]])

In [ ]:
squares = [x ** 2 for x in range(1, 11)]

In [ ]:
squares

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
even_squares = [x ** 2 for x in range(1, 6) if x % 2 == 0]

In [ ]:
even_squares

[4, 16]

In [ ]:
odd_squares = [x ** 2 for x in range(1, 6) if x % 2 != 0]

In [ ]:
odd_squares

[1, 9, 25]

In [ ]:
x_size = 2
y_size = 3
z_size = 4
three_dimensional_list = [[[10 for _ in range(x_size)] for _ in range(y_size)] for _ in range(z_size)]

In [ ]:
three_dimensional_list

[[[10, 10], [10, 10], [10, 10]],
 [[10, 10], [10, 10], [10, 10]],
 [[10, 10], [10, 10], [10, 10]],
 [[10, 10], [10, 10], [10, 10]]]

In [ ]:
import numpy as np

In [ ]:
nos = np.arange(1, 11)

In [ ]:
nos

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
nos2 = nos.view()

In [ ]:
id(nos)

132878273181520

In [ ]:
id(nos2)

132878273178928

In [ ]:
nos2

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

In [ ]:
nos[9] *= 10

In [ ]:
nos

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
nos2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
nos2[0] /= 10

In [ ]:
nos2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
nos

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
nos2 = nos[0:5]

In [ ]:
nos2

array([1, 2, 3, 4, 5])

In [ ]:
nos[2] *= 100

In [ ]:
nos

array([  1,   2, 300,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
nos2

array([  1,   2, 300,   4,   5])

In [ ]:
import numpy as np

In [ ]:
num = np.arange(1 , 6)

In [ ]:
num

array([1, 2, 3, 4, 5])

In [ ]:
num2 = num.copy()

In [ ]:
num2

array([1, 2, 3, 4, 5])

In [ ]:
num[3] *= 10

In [ ]:
num

array([ 1,  2,  3, 40,  5])

In [ ]:
num2

array([1, 2, 3, 4, 5])

In [ ]:
num2[1] *= 10

In [ ]:
num

array([ 1,  2,  3, 40,  5])

In [ ]:
num2

array([ 1, 20,  3,  4,  5])

In [ ]:
id(num)

139990808992656

In [ ]:
id(num2)

139991013487312

In [ ]:
import numpy as np

In [ ]:
gr = np.array([[9, 10, 8, 9] , [8, 10, 10, 9]])

In [ ]:
gr

array([[ 9, 10,  8,  9],
       [ 8, 10, 10,  9]])

In [ ]:
gr.reshape(1, 8)

array([[ 9, 10,  8,  9,  8, 10, 10,  9]])

In [ ]:
gr

array([[ 9, 10,  8,  9],
       [ 8, 10, 10,  9]])

In [ ]:
gr.resize(1, 8)

In [ ]:
gr

array([[ 9, 10,  8,  9,  8, 10, 10,  9]])

In [ ]:
grf = gr.flatten()

In [ ]:
grf

array([ 9, 10,  8,  9,  8, 10, 10,  9])

In [ ]:
gr_r = gr.ravel()

In [ ]:
gr_r

array([ 9, 10,  8,  9,  8, 10, 10,  9])

In [ ]:
import numpy as np

In [ ]:
a = np.array([[10, 9, 8, 7] , [6, 5, 4, 3]])

In [ ]:
a.T

array([[10,  6],
       [ 9,  5],
       [ 8,  4],
       [ 7,  3]])

In [ ]:
a2 = np.array([[1, 2, 3, 4] , [5, 6, 7, 8]])

In [ ]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a , a2))

array([[10,  9,  8,  7,  1,  2,  3,  4],
       [ 6,  5,  4,  3,  5,  6,  7,  8]])

In [ ]:
np.vstack((a , a2))

array([[10,  9,  8,  7],
       [ 6,  5,  4,  3],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

                                                                             
                                                                              
                                                         This is the END