In [1]:
import numpy as np
from scipy.signal import convolve2d

# Assume the 6x6 random matrix as:
input_array_6x6 = np.array([
    [45, 48, 65, 68, 68, 10],
    [84, 22, 37, 88, 71, 89],
    [89, 13, 59, 66, 40, 88],
    [47, 89, 82, 38, 26, 78],
    [73, 93, 77, 38, 44, 12],
    [30, 51, 60, 76, 54, 68]
])

# Random 3x3 filter
filter_array = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

# Perform Convolution for each case

# Case 1: No Padding, Stride=1
output_case_1 = convolve2d(input_array_6x6, filter_array, mode='valid')

# Case 2: Padding, Stride=1
output_case_2 = convolve2d(input_array_6x6, filter_array, mode='same')

# Case 3: No Padding, Stride=2
# Using slicing to simulate stride of 2 for case 3 and 4
output_case_3 = convolve2d(input_array_6x6, filter_array, mode='valid')[::2, ::2]

# Case 4: Padding, Stride=2
output_case_4 = convolve2d(input_array_6x6, filter_array, mode='same')[::2, ::2]

# Print the output for each case
print("Case 1: No Padding, Stride=1")
print(output_case_1)
print("\nCase 2: Padding, Stride=1")
print(output_case_2)
print("\nCase 3: No Padding, Stride=2")
print(output_case_3)
print("\nCase 4: Padding, Stride=2")
print(output_case_4)


Case 1: No Padding, Stride=1
[[  57 -139  -18   35]
 [  42  -68   41  -63]
 [  -9   53  108  -36]
 [ -69   81   95   -6]]

Case 2: Padding, Stride=1
[[ -70   27  -86  -37   57  139]
 [ -83   57 -139  -18   35  179]
 [-124   42  -68   41  -63  137]
 [-195   -9   53  108  -36  110]
 [-233  -69   81   95   -6  124]
 [-144  -34   30   39   34   98]]

Case 3: No Padding, Stride=2
[[ 57 -18]
 [ -9 108]]

Case 4: Padding, Stride=2
[[ -70  -86   57]
 [-124  -68  -63]
 [-233   81   -6]]


In [3]:
import numpy as np
from scipy.signal import convolve2d

# Assume the 5x5 random matrix as:
input_array_5x5 = np.array([
    [5, 8, 5, 8, 6],
    [4, 2, 3, 8, 7],
    [9, 1, 5, 6, 0],
    [7, 9, 2, 3, 2],
    [3, 3, 7, 8, 4]
])

# Random 3x3 filter
filter_array = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

def convolve_with_stride(input_array, filter_array, stride):
    output_shape = (
        (input_array.shape[0] - filter_array.shape[0]) // stride + 1,
        (input_array.shape[1] - filter_array.shape[1]) // stride + 1
    )
    output_array = np.zeros(output_shape)
    for i in range(0, output_shape[0]):
        for j in range(0, output_shape[1]):
            output_array[i, j] = np.sum(
                input_array[i*stride:i*stride+filter_array.shape[0],
                            j*stride:j*stride+filter_array.shape[1]] * filter_array
            )
    return output_array

# Perform Convolution for each case

# Case 1: No Padding, Stride=1
output_case_1 = convolve2d(input_array_5x5, filter_array, mode='valid')

# Case 2: Padding, Stride=1
output_case_2 = convolve2d(input_array_5x5, filter_array, mode='same')

# Case 3: No Padding, Stride=2
output_case_3 = convolve_with_stride(input_array_5x5, filter_array, stride=2)

# Case 4: Padding, Stride=2
# First pad the input array
padded_array = np.pad(input_array_5x5, pad_width=1, mode='constant')
output_case_4 = convolve_with_stride(padded_array, filter_array, stride=2)

# Print the output for each case
print("Case 1: No Padding, Stride=1")
print(output_case_1)
print("\nCase 2: Padding, Stride=1")
print(output_case_2)
print("\nCase 3: No Padding, Stride=2")
print(output_case_3)
print("\nCase 4: Padding, Stride=2")
print(output_case_4)


Case 1: No Padding, Stride=1
[[  5 -11   0]
 [ 10  -5   1]
 [  5  -4   8]]

Case 2: Padding, Stride=1
[[-10   1  -6  -5  16]
 [-11   5 -11   0  22]
 [-12  10  -5   1  17]
 [-13   5  -4   8  17]
 [-12   1   1   3  11]]

Case 3: No Padding, Stride=2
[[-5.  0.]
 [-5. -8.]]

Case 4: Padding, Stride=2
[[ 10.   6. -16.]
 [ 12.   5. -17.]
 [ 12.  -1. -11.]]
