In [2]:
import numpy as np

# Your original array
original_array = np.array([
    [5, 8, 5, 8, 6],
    [4, 2, 3, 8, 7],
    [9, 1, 5, 6, 0],
    [7, 9, 2, 3, 2],
    [3, 3, 7, 8, 4]
])

# Refill with random numbers from 0 to 9
refilled_array = np.random.randint(0, 10, size=original_array.shape)

print(refilled_array)


[[5 6 7 4 4]
 [9 0 3 1 3]
 [8 1 6 7 4]
 [3 9 9 6 5]
 [8 2 5 2 9]]
