In [ ]:
1+1
2+3








5

My initial program

In [ ]:
32//8

4

In [ ]:
a = 300.2
b = 400

In [ ]:
type(a)

float

In [ ]:
print(a)
print(b)

300.02
400


In [ ]:
# comment ignored by the interpreter
a
b

400

###Trial Examples


In [ ]:
a = "Hello world"

In [ ]:
print(a)

Hello world


In [ ]:
a != b

True

In [ ]:
a > b

False

In [ ]:
a < b

True

In [ ]:
a = 3
b = 4.2

In [ ]:
print( a>b and b != 5)

False


In [ ]:
print (float(a))
print (int(b))
print (bin(a))
print (hex(a))
print (oct(a))
oct_a = oct(a)
print(oct_a)
print(int(oct_a,8))

3.0
4
0b11
0x3
0o3
0o3
3


In [ ]:
print (int('0xaa',16))

170


In [ ]:
print (int(7.7))

7


In [ ]:
print (round(5.1234))
print (round(5.12945, 2))

5
5.13


In [ ]:
c = complex('5+2j')

In [ ]:
print (abs(c))

5.385164807134504


In [ ]:
abc = input("Type something here \t")

In [ ]:
abc

'python class'

In [ ]:
type(abc)

str

In [ ]:
dir(abc)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [ ]:
print(5.0.__add__(4.0))

In [ ]:
string = "Python Class"
string.

'PYTHON CLASS'

In [ ]:
my_name = "Daniel"
string = "Hello, {0}!"
print(string.format(my_name))

Hello, Daniel!


In [ ]:
"{0} likes {1}".format("Everybody", "Python")

'Everybody likes Python'

In [ ]:
my_name = 'Phil'+' '+'Dani'

In [ ]:
my_name

'Phil Dani'

In [ ]:
line = '=' * 10
line

'=========='

In [ ]:
len(my_name)

9

In [ ]:
print(1 + int('2'))

3


In [ ]:
print(str(1)+'2')
cap = (str(1)+'2')

12


In [ ]:
type(cap)

str

In [ ]:
print ("string to float:", float("3.5"))

string to float: 3.5


In [ ]:
total = 0
for number in range (100,1,-2):
  total += number

print(total)

In [ ]:
if a > 700:
  print ('a is greater than 100')
elif b > 600:
  print ('b is greater than 600')
  


In [ ]:
valid = True
while valid:
  Print("while")
  Valid=False

In [ ]:
fruits = ['apple', 'orange', 'grape']
Jumbled = ['apple', 1, True]

In [ ]:
fruits[3]

IndexError: ignored

In [ ]:
len(fruits)

3

In [ ]:
#            0        1        2       3       4
#           -5       -4      -3       -2        -1   
fruits = ['apple', 'orange', 'grape','peach','berry']
fruits[-1]

'berry'

In [ ]:
fruits

['peach', 'orange', 'grape']

In [ ]:
#SLICING
fruits[1:4]

['orange', 'grape', 'peach']

In [ ]:
fruits[:4]

['apple', 'orange', 'grape', 'peach']

In [ ]:
fruits[2:]

['grape', 'peach', 'berry']

In [ ]:
fruits[::-1]

['berry', 'peach', 'grape', 'orange', 'apple']

In [ ]:
fruits[-4:-1]

['orange', 'grape', 'peach']

In [ ]:
fruits.append('mango')

In [ ]:
fruits

['apple', 'orange', 'grape', 'peach', 'berry', 'mango']

In [ ]:
my_tuple = (1,2,3,4,5)

In [ ]:
for num in my_tuple:
  print(num)

1
2
3
4
5


In [ ]:
my_tuple[2] = 7

TypeError: ignored

In [ ]:
new = [1,2,3,4]
another = [5,6,7]
new.extend(another)
print(new)

[1, 2, 3, 4, 5, 6, 7]


In [ ]:
new = [1,2,3,4]
another = [5,6,7]
new.append(another)
old = [9,8,7,6]
old.append(another)
new.append(old)
print(new)

[1, 2, 3, 4, [5, 6, 7], [9, 8, 7, 6, [5, 6, 7]]]


In [ ]:
new[4][1]

6

In [ ]:
my_types = ([1,2,3], "name", 1, 2)
new.append(my_types)
new

[1,
 2,
 3,
 4,
 [5, 6, 7],
 [9, 8, 7, 6, [5, 6, 7]],
 ([1, 2, 3], 'name', 1, 2),
 ([1, 2, 3], 'name', 1, 2)]

In [ ]:
my_dict = {"name":"Dani", "height":5.8}
my_dict["height"]

5.8

In [ ]:
my_dict["name"]="Raj"

In [ ]:
my_dict

{'height': 5.8, 'name': 'Raj'}

In [ ]:
import numpy as np

In [ ]:
numbers = [1,2,3,4,5]

In [ ]:
numbers_np = np.array(number)

In [ ]:
print(numbers_np)

99


In [ ]:
type(numbers_np)

numpy.ndarray

In [ ]:
numbers_np = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
numbers_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
numbers_np.shape

(3, 3)

In [ ]:
array0 = np.zeros((3,4))

In [ ]:
array0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array1 = np.zeros((3,4))

In [ ]:
array1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arrayid = np.eye(4,4)

In [ ]:
arrayid

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
numbers_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
numbers_np[:1]

array([[1, 2, 3]])

In [ ]:
numbers_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
numbers_np_bool = numbers_np%2==0

In [ ]:
numbers_np_bool

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [ ]:
numbers_np[numbers_np_bool]

array([2, 4, 6, 8])

In [ ]:
numbers_np*4

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [ ]:
num_to_add = np.arange(3)

In [ ]:
num_to_add

array([0, 1, 2])

In [ ]:
numbers_np + num_to_add

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])